import ServicesClient  from "./ServicesClient";

export const metadata = {
  title: "Our Services - Progronics | IT Solutions & Development",
  description:
    "Explore our comprehensive IT solutions including web and mobile app development, custom software engineering, UI/UX design, branding, embedded systems, staff augmentation, and digital transformation services.",
  keywords: [
    "IT services",
    "IT solutions company",
    "software development services",
    "custom software development",
    "web development services",
    "mobile app development services",
    "android app development",
    "iOS app development",
    "cross platform app development",
    "React development",
    "Next.js development",
    "Node.js development",
    "full stack development",
    "frontend development",
    "backend development",
    "API development",
    "SaaS development",
    "startup development",
    "enterprise software",
    "software consultancy",
    "technology consulting",
    "IT consulting services",
    "digital transformation services",
    "UI UX design",
    "user interface design",
    "user experience design",
    "brand identity design",
    "branding services",
    "logo design",
    "social media branding",
    "social media marketing",
    "digital marketing services",
    "embedded systems development",
    "IoT development",
    "hardware programming",
    "microcontroller programming",
    "firmware development",
    "staff augmentation",
    "IT staffing solutions",
    "remote developers",
    "hire dedicated developers",
    "dedicated development team",
    "IT outsourcing",
    "offshore development",
    "nearshore development",
    "software maintenance",
    "software optimization",
    "performance optimization",
    "technical support",
    "IT support services",
    "technology agency",
    "IT company",
    "software house",
    "IT solutions provider",
    "custom IT solutions",
    "Progronics",
    "IT services Pakistan",
    "software company Pakistan",
    "development agency Pakistan",
  ],
};


export default function ServicesPage() {
  return <ServicesClient />
}
